name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: 迁出代码
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@master

      # 安装Node14
      - name: 安装node.js
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 14.0.0

      # 安装前端依赖
      - name: 安装前端依赖并且打包
        run: |
          cd react-admin-client
          npm install
          npm run build
      # 安装后端依赖
      - name: 安装后端依赖并且打包
        run: |
          cd react-admin-server
          npm install
          npm run build

      # 上传前端静态资源到服务器
      - name: 发布前端
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # scp参数
          ARGS: "-rltgoDzvO --delete"
          # 源目录
          SOURCE: "react-admin-client/client"
          # 服务器ip
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # 用户
          REMOTE_USER: "root"
          # 目标地址
          TARGET: "/www/wwwroot/client"

      # 上传后端静态资源到服务器
      - name: 发布后端
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # scp参数
          ARGS: "-rltgoDzvO --delete"
          # 源目录
          SOURCE: "react-admin-server/server"
          # 服务器ip
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # 用户
          REMOTE_USER: "root"
          # 目标地址
          TARGET: "/www/wwwroot/server"
